// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "rocc0_vadd.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic rocc0_vadd::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic rocc0_vadd::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state1 = "1";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state2 = "10";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state3 = "100";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state4 = "1000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state5 = "10000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state6 = "100000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state7 = "1000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state8 = "10000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state9 = "100000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state10 = "1000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state11 = "10000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state12 = "100000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state41 = "10000000000000000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state42 = "100000000000000000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state43 = "1000000000000000000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state44 = "10000000000000000000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state45 = "100000000000000000000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state46 = "1000000000000000000000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state47 = "10000000000000000000000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state48 = "100000000000000000000000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state49 = "1000000000000000000000000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state50 = "10000000000000000000000000000000000000000000000000";
const sc_lv<51> rocc0_vadd::ap_ST_fsm_state51 = "100000000000000000000000000000000000000000000000000";
const sc_lv<32> rocc0_vadd::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> rocc0_vadd::ap_const_lv32_2 = "10";
const sc_lv<32> rocc0_vadd::ap_const_lv32_3 = "11";
const sc_lv<32> rocc0_vadd::ap_const_lv32_4 = "100";
const sc_lv<1> rocc0_vadd::ap_const_lv1_0 = "0";
const sc_lv<32> rocc0_vadd::ap_const_lv32_5 = "101";
const sc_lv<32> rocc0_vadd::ap_const_lv32_7 = "111";
const sc_lv<32> rocc0_vadd::ap_const_lv32_8 = "1000";
const sc_lv<32> rocc0_vadd::ap_const_lv32_A = "1010";
const sc_lv<32> rocc0_vadd::ap_const_lv32_C = "1100";
const sc_lv<32> rocc0_vadd::ap_const_lv32_D = "1101";
const sc_lv<32> rocc0_vadd::ap_const_lv32_F = "1111";
const sc_lv<32> rocc0_vadd::ap_const_lv32_11 = "10001";
const sc_lv<32> rocc0_vadd::ap_const_lv32_12 = "10010";
const sc_lv<32> rocc0_vadd::ap_const_lv32_13 = "10011";
const sc_lv<32> rocc0_vadd::ap_const_lv32_14 = "10100";
const sc_lv<32> rocc0_vadd::ap_const_lv32_16 = "10110";
const sc_lv<32> rocc0_vadd::ap_const_lv32_17 = "10111";
const sc_lv<32> rocc0_vadd::ap_const_lv32_19 = "11001";
const sc_lv<32> rocc0_vadd::ap_const_lv32_1B = "11011";
const sc_lv<32> rocc0_vadd::ap_const_lv32_1C = "11100";
const sc_lv<32> rocc0_vadd::ap_const_lv32_1D = "11101";
const sc_lv<32> rocc0_vadd::ap_const_lv32_1E = "11110";
const sc_lv<32> rocc0_vadd::ap_const_lv32_20 = "100000";
const sc_lv<32> rocc0_vadd::ap_const_lv32_21 = "100001";
const sc_lv<32> rocc0_vadd::ap_const_lv32_23 = "100011";
const sc_lv<32> rocc0_vadd::ap_const_lv32_25 = "100101";
const sc_lv<32> rocc0_vadd::ap_const_lv32_26 = "100110";
const sc_lv<32> rocc0_vadd::ap_const_lv32_27 = "100111";
const sc_lv<32> rocc0_vadd::ap_const_lv32_28 = "101000";
const sc_lv<32> rocc0_vadd::ap_const_lv32_2A = "101010";
const sc_lv<32> rocc0_vadd::ap_const_lv32_2B = "101011";
const sc_lv<32> rocc0_vadd::ap_const_lv32_2D = "101101";
const sc_lv<1> rocc0_vadd::ap_const_lv1_1 = "1";
const sc_lv<32> rocc0_vadd::ap_const_lv32_2E = "101110";
const sc_lv<32> rocc0_vadd::ap_const_lv32_30 = "110000";
const sc_lv<32> rocc0_vadd::ap_const_lv32_31 = "110001";
const sc_lv<32> rocc0_vadd::ap_const_lv32_2C = "101100";
const sc_lv<32> rocc0_vadd::ap_const_lv32_32 = "110010";
const sc_lv<32> rocc0_vadd::ap_const_lv32_9 = "1001";
const sc_lv<32> rocc0_vadd::ap_const_lv32_E = "1110";
const sc_lv<32> rocc0_vadd::ap_const_lv32_18 = "11000";
const sc_lv<32> rocc0_vadd::ap_const_lv32_22 = "100010";
const sc_lv<32> rocc0_vadd::ap_const_lv32_1 = "1";
const sc_lv<32> rocc0_vadd::ap_const_lv32_1F = "11111";
const sc_lv<3> rocc0_vadd::ap_const_lv3_0 = "000";
const sc_lv<32> rocc0_vadd::ap_const_lv32_FFFFFFF9 = "11111111111111111111111111111001";
const sc_lv<29> rocc0_vadd::ap_const_lv29_0 = "00000000000000000000000000000";
const sc_lv<33> rocc0_vadd::ap_const_lv33_1 = "1";
const sc_lv<64> rocc0_vadd::ap_const_lv64_1 = "1";
const sc_lv<32> rocc0_vadd::ap_const_lv32_6 = "110";
const bool rocc0_vadd::ap_const_boolean_1 = true;

rocc0_vadd::rocc0_vadd(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_0_sum1_cast_fu_501_p1);
    sensitive << ( a_0_sum1_fu_495_p2 );

    SC_METHOD(thread_a_0_sum1_fu_495_p2);
    sensitive << ( tmp_2_cast_fu_491_p1 );

    SC_METHOD(thread_a_0_sum2_fu_543_p2);
    sensitive << ( tmp_7_fu_539_p1 );

    SC_METHOD(thread_a_0_sum3_fu_592_p2);
    sensitive << ( tmp_10_fu_588_p1 );

    SC_METHOD(thread_a_0_sum4_fu_694_p2);
    sensitive << ( tmp_20_fu_690_p1 );

    SC_METHOD(thread_a_0_sum5_fu_796_p2);
    sensitive << ( tmp_30_fu_792_p1 );

    SC_METHOD(thread_a_0_sum6_cast_fu_646_p1);
    sensitive << ( a_0_sum6_fu_640_p2 );

    SC_METHOD(thread_a_0_sum6_fu_640_p2);
    sensitive << ( tmp_17_cast_fu_636_p1 );

    SC_METHOD(thread_a_0_sum7_cast_fu_850_p1);
    sensitive << ( a_0_sum7_fu_844_p2 );

    SC_METHOD(thread_a_0_sum7_fu_844_p2);
    sensitive << ( tmp_41_cast_fu_840_p1 );

    SC_METHOD(thread_a_0_sum9_cast_fu_748_p1);
    sensitive << ( a_0_sum9_fu_742_p2 );

    SC_METHOD(thread_a_0_sum9_fu_742_p2);
    sensitive << ( tmp_29_cast_fu_738_p1 );

    SC_METHOD(thread_a_0_sum_cast_fu_909_p1);
    sensitive << ( a_0_sum_fu_903_p2 );

    SC_METHOD(thread_a_0_sum_fu_903_p2);
    sensitive << ( tmp_47_cast_fu_899_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state29);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state30);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state31);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state33);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state34);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state35);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state36);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state38);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state39);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state40);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state41);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state43);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state44);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state45);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state46);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state47);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state49);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state50);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state51);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state13);
    sensitive << ( length_a_rsp_empty_n );
    sensitive << ( b_c_rsp_empty_n );

    SC_METHOD(thread_ap_block_state18);
    sensitive << ( length_a_rsp_empty_n );
    sensitive << ( b_c_rsp_empty_n );

    SC_METHOD(thread_ap_block_state23);
    sensitive << ( length_a_rsp_empty_n );
    sensitive << ( b_c_rsp_empty_n );

    SC_METHOD(thread_ap_block_state28);
    sensitive << ( length_a_rsp_empty_n );
    sensitive << ( b_c_rsp_empty_n );

    SC_METHOD(thread_ap_block_state33);
    sensitive << ( length_a_rsp_empty_n );
    sensitive << ( b_c_rsp_empty_n );

    SC_METHOD(thread_ap_block_state38);
    sensitive << ( length_a_rsp_empty_n );
    sensitive << ( b_c_rsp_empty_n );

    SC_METHOD(thread_ap_block_state43);
    sensitive << ( length_a_rsp_empty_n );
    sensitive << ( b_c_rsp_empty_n );

    SC_METHOD(thread_ap_block_state49);
    sensitive << ( length_a_rsp_empty_n );
    sensitive << ( b_c_rsp_empty_n );

    SC_METHOD(thread_ap_block_state8);
    sensitive << ( length_a_rsp_empty_n );
    sensitive << ( b_c_rsp_empty_n );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state46 );
    sensitive << ( tmp_39_fu_894_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state46 );
    sensitive << ( tmp_39_fu_894_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state46 );
    sensitive << ( tmp_39_fu_894_p2 );

    SC_METHOD(thread_b_c_address);
    sensitive << ( b_c_req_full_n );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( ap_CS_fsm_state36 );
    sensitive << ( ap_CS_fsm_state40 );
    sensitive << ( ap_CS_fsm_state41 );
    sensitive << ( ap_CS_fsm_state47 );
    sensitive << ( ap_CS_fsm_state45 );
    sensitive << ( ap_CS_fsm_state51 );
    sensitive << ( tmp_2_fu_511_p1 );
    sensitive << ( tmp_6_fu_529_p1 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_7_fu_539_p1 );
    sensitive << ( tmp_s_fu_572_p1 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( tmp_10_fu_588_p1 );
    sensitive << ( tmp_13_fu_620_p1 );
    sensitive << ( tmp_15_fu_656_p1 );
    sensitive << ( tmp_18_fu_674_p1 );
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( tmp_20_fu_690_p1 );
    sensitive << ( tmp_23_fu_722_p1 );
    sensitive << ( tmp_25_fu_758_p1 );
    sensitive << ( tmp_28_fu_776_p1 );
    sensitive << ( ap_CS_fsm_state35 );
    sensitive << ( tmp_30_fu_792_p1 );
    sensitive << ( tmp_33_fu_824_p1 );
    sensitive << ( tmp_35_fu_866_p1 );
    sensitive << ( tmp_38_fu_884_p1 );
    sensitive << ( tmp_40_fu_919_p1 );
    sensitive << ( tmp_43_fu_945_p1 );

    SC_METHOD(thread_b_c_dataout);
    sensitive << ( b_c_req_full_n );
    sensitive << ( tmp_3_reg_1016 );
    sensitive << ( tmp_8_reg_1048 );
    sensitive << ( tmp_11_reg_1085 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( tmp_16_reg_1123 );
    sensitive << ( tmp_21_reg_1160 );
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( tmp_26_reg_1198 );
    sensitive << ( tmp_31_reg_1235 );
    sensitive << ( ap_CS_fsm_state40 );
    sensitive << ( tmp_36_reg_1283 );
    sensitive << ( tmp_41_reg_1313 );
    sensitive << ( ap_CS_fsm_state45 );
    sensitive << ( ap_CS_fsm_state51 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( ap_CS_fsm_state35 );

    SC_METHOD(thread_b_c_req_din);
    sensitive << ( b_c_req_full_n );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( ap_CS_fsm_state36 );
    sensitive << ( ap_CS_fsm_state40 );
    sensitive << ( ap_CS_fsm_state41 );
    sensitive << ( ap_CS_fsm_state47 );
    sensitive << ( ap_CS_fsm_state45 );
    sensitive << ( ap_CS_fsm_state51 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( ap_CS_fsm_state35 );

    SC_METHOD(thread_b_c_req_write);
    sensitive << ( b_c_req_full_n );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( ap_CS_fsm_state36 );
    sensitive << ( ap_CS_fsm_state40 );
    sensitive << ( ap_CS_fsm_state41 );
    sensitive << ( ap_CS_fsm_state47 );
    sensitive << ( ap_CS_fsm_state45 );
    sensitive << ( ap_CS_fsm_state51 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( ap_CS_fsm_state35 );

    SC_METHOD(thread_b_c_rsp_read);
    sensitive << ( length_a_rsp_empty_n );
    sensitive << ( b_c_rsp_empty_n );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( ap_CS_fsm_state28 );
    sensitive << ( ap_CS_fsm_state33 );
    sensitive << ( ap_CS_fsm_state38 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( ap_CS_fsm_state49 );

    SC_METHOD(thread_b_c_size);
    sensitive << ( b_c_req_full_n );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( ap_CS_fsm_state36 );
    sensitive << ( ap_CS_fsm_state40 );
    sensitive << ( ap_CS_fsm_state41 );
    sensitive << ( ap_CS_fsm_state47 );
    sensitive << ( ap_CS_fsm_state45 );
    sensitive << ( ap_CS_fsm_state51 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( ap_CS_fsm_state35 );

    SC_METHOD(thread_i_2_fu_860_p2);
    sensitive << ( i_reg_364 );

    SC_METHOD(thread_i_3_fu_939_p2);
    sensitive << ( i_1_reg_376 );

    SC_METHOD(thread_i_5_fu_396_p3);
    sensitive << ( tmp_44_reg_970 );

    SC_METHOD(thread_i_5_op_op_fu_410_p2);
    sensitive << ( i_5_fu_396_p3 );

    SC_METHOD(thread_length_a_address);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( length_a_addr_reg_994 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( length_a_addr_3_reg_1101 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( length_a_addr_5_reg_1176 );
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( ap_CS_fsm_state36 );
    sensitive << ( length_a_addr_7_reg_1251 );
    sensitive << ( ap_CS_fsm_state41 );
    sensitive << ( length_a_addr_8_reg_1291 );
    sensitive << ( ap_CS_fsm_state47 );
    sensitive << ( a_0_sum2_fu_543_p2 );
    sensitive << ( a_0_sum3_fu_592_p2 );
    sensitive << ( a_0_sum4_fu_694_p2 );
    sensitive << ( a_0_sum5_fu_796_p2 );

    SC_METHOD(thread_length_a_dataout);

    SC_METHOD(thread_length_a_req_din);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( ap_CS_fsm_state36 );
    sensitive << ( ap_CS_fsm_state41 );
    sensitive << ( ap_CS_fsm_state47 );

    SC_METHOD(thread_length_a_req_write);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( ap_CS_fsm_state36 );
    sensitive << ( ap_CS_fsm_state41 );
    sensitive << ( ap_CS_fsm_state47 );

    SC_METHOD(thread_length_a_rsp_read);
    sensitive << ( length_a_rsp_empty_n );
    sensitive << ( b_c_rsp_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( ap_CS_fsm_state28 );
    sensitive << ( ap_CS_fsm_state33 );
    sensitive << ( ap_CS_fsm_state38 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( ap_CS_fsm_state49 );

    SC_METHOD(thread_length_a_size);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( ap_CS_fsm_state36 );
    sensitive << ( ap_CS_fsm_state41 );
    sensitive << ( ap_CS_fsm_state47 );

    SC_METHOD(thread_p_lshr_fu_430_p4);
    sensitive << ( p_neg_fu_424_p2 );

    SC_METHOD(thread_p_neg_fu_424_p2);
    sensitive << ( i_5_fu_396_p3 );

    SC_METHOD(thread_p_neg_t_fu_440_p2);
    sensitive << ( p_lshr_fu_430_p4 );

    SC_METHOD(thread_tmp_10_fu_588_p1);
    sensitive << ( tmp_4_fu_582_p2 );

    SC_METHOD(thread_tmp_11_fu_612_p2);
    sensitive << ( length_a_addr_2_read_reg_1075 );
    sensitive << ( b_c_addr_4_read_reg_1080 );

    SC_METHOD(thread_tmp_12_fu_616_p2);
    sensitive << ( length_reg_955 );
    sensitive << ( tmp_4_reg_1058 );

    SC_METHOD(thread_tmp_13_fu_620_p1);
    sensitive << ( tmp_12_reg_1090 );

    SC_METHOD(thread_tmp_14_fu_630_p2);
    sensitive << ( i_reg_364 );

    SC_METHOD(thread_tmp_15_fu_656_p1);
    sensitive << ( tmp_14_reg_1095 );

    SC_METHOD(thread_tmp_16_fu_666_p2);
    sensitive << ( length_a_addr_3_read_reg_1113 );
    sensitive << ( b_c_addr_6_read_reg_1118 );

    SC_METHOD(thread_tmp_17_cast_fu_636_p1);
    sensitive << ( tmp_14_fu_630_p2 );

    SC_METHOD(thread_tmp_17_fu_670_p2);
    sensitive << ( length_reg_955 );
    sensitive << ( tmp_14_reg_1095 );

    SC_METHOD(thread_tmp_18_fu_674_p1);
    sensitive << ( tmp_17_reg_1128 );

    SC_METHOD(thread_tmp_19_fu_684_p2);
    sensitive << ( i_reg_364 );

    SC_METHOD(thread_tmp_1_fu_485_p2);
    sensitive << ( i_reg_364 );

    SC_METHOD(thread_tmp_20_fu_690_p1);
    sensitive << ( tmp_19_fu_684_p2 );

    SC_METHOD(thread_tmp_21_fu_714_p2);
    sensitive << ( length_a_addr_4_read_reg_1150 );
    sensitive << ( b_c_addr_8_read_reg_1155 );

    SC_METHOD(thread_tmp_22_fu_718_p2);
    sensitive << ( length_reg_955 );
    sensitive << ( tmp_19_reg_1133 );

    SC_METHOD(thread_tmp_23_fu_722_p1);
    sensitive << ( tmp_22_reg_1165 );

    SC_METHOD(thread_tmp_24_fu_732_p2);
    sensitive << ( i_reg_364 );

    SC_METHOD(thread_tmp_25_fu_758_p1);
    sensitive << ( tmp_24_reg_1170 );

    SC_METHOD(thread_tmp_26_fu_768_p2);
    sensitive << ( length_a_addr_5_read_reg_1188 );
    sensitive << ( b_c_addr_10_read_reg_1193 );

    SC_METHOD(thread_tmp_27_fu_772_p2);
    sensitive << ( length_reg_955 );
    sensitive << ( tmp_24_reg_1170 );

    SC_METHOD(thread_tmp_28_fu_776_p1);
    sensitive << ( tmp_27_reg_1203 );

    SC_METHOD(thread_tmp_29_cast_fu_738_p1);
    sensitive << ( tmp_24_fu_732_p2 );

    SC_METHOD(thread_tmp_29_fu_786_p2);
    sensitive << ( i_reg_364 );

    SC_METHOD(thread_tmp_2_cast_fu_491_p1);
    sensitive << ( tmp_1_fu_485_p2 );

    SC_METHOD(thread_tmp_2_fu_511_p1);
    sensitive << ( tmp_1_reg_988 );

    SC_METHOD(thread_tmp_30_fu_792_p1);
    sensitive << ( tmp_29_fu_786_p2 );

    SC_METHOD(thread_tmp_31_fu_816_p2);
    sensitive << ( length_a_addr_6_read_reg_1225 );
    sensitive << ( b_c_addr_12_read_reg_1230 );

    SC_METHOD(thread_tmp_32_fu_820_p2);
    sensitive << ( length_reg_955 );
    sensitive << ( tmp_29_reg_1208 );

    SC_METHOD(thread_tmp_33_fu_824_p1);
    sensitive << ( tmp_32_reg_1240 );

    SC_METHOD(thread_tmp_34_fu_834_p2);
    sensitive << ( i_reg_364 );

    SC_METHOD(thread_tmp_35_fu_866_p1);
    sensitive << ( tmp_34_reg_1245 );

    SC_METHOD(thread_tmp_36_fu_880_p2);
    sensitive << ( length_a_addr_7_read_reg_1273 );
    sensitive << ( b_c_addr_14_read_reg_1278 );

    SC_METHOD(thread_tmp_37_fu_876_p2);
    sensitive << ( length_reg_955 );
    sensitive << ( tmp_34_reg_1245 );

    SC_METHOD(thread_tmp_38_fu_884_p1);
    sensitive << ( tmp_37_reg_1268 );

    SC_METHOD(thread_tmp_39_fu_894_p2);
    sensitive << ( length_reg_955 );
    sensitive << ( ap_CS_fsm_state46 );
    sensitive << ( i_1_reg_376 );

    SC_METHOD(thread_tmp_3_fu_521_p2);
    sensitive << ( length_a_addr_read_reg_1006 );
    sensitive << ( b_c_addr_read_reg_1011 );

    SC_METHOD(thread_tmp_40_fu_919_p1);
    sensitive << ( i_1_reg_376 );

    SC_METHOD(thread_tmp_41_cast_fu_840_p1);
    sensitive << ( tmp_34_fu_834_p2 );

    SC_METHOD(thread_tmp_41_fu_930_p2);
    sensitive << ( length_a_addr_8_read_reg_1303 );
    sensitive << ( b_c_addr_16_read_reg_1308 );

    SC_METHOD(thread_tmp_42_fu_934_p2);
    sensitive << ( length_reg_955 );
    sensitive << ( i_1_reg_376 );

    SC_METHOD(thread_tmp_43_fu_945_p1);
    sensitive << ( tmp_42_reg_1318 );

    SC_METHOD(thread_tmp_45_fu_416_p3);
    sensitive << ( i_5_op_op_fu_410_p2 );

    SC_METHOD(thread_tmp_46_fu_446_p4);
    sensitive << ( i_5_op_op_fu_410_p2 );

    SC_METHOD(thread_tmp_47_cast_fu_899_p1);
    sensitive << ( i_1_reg_376 );

    SC_METHOD(thread_tmp_47_fu_456_p3);
    sensitive << ( tmp_45_fu_416_p3 );
    sensitive << ( p_neg_t_fu_440_p2 );
    sensitive << ( tmp_46_fu_446_p4 );

    SC_METHOD(thread_tmp_48_fu_464_p3);
    sensitive << ( tmp_fu_403_p3 );
    sensitive << ( tmp_47_fu_456_p3 );

    SC_METHOD(thread_tmp_49_fu_472_p3);
    sensitive << ( tmp_48_fu_464_p3 );

    SC_METHOD(thread_tmp_4_fu_582_p2);
    sensitive << ( i_reg_364 );

    SC_METHOD(thread_tmp_50_fu_480_p2);
    sensitive << ( tmp_49_reg_980 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i_reg_364 );

    SC_METHOD(thread_tmp_5_fu_525_p2);
    sensitive << ( length_reg_955 );
    sensitive << ( tmp_1_reg_988 );

    SC_METHOD(thread_tmp_6_fu_529_p1);
    sensitive << ( tmp_5_reg_1021 );

    SC_METHOD(thread_tmp_7_fu_539_p1);
    sensitive << ( i_reg_364 );

    SC_METHOD(thread_tmp_8_fu_563_p2);
    sensitive << ( length_a_addr_1_read_reg_1038 );
    sensitive << ( b_c_addr_2_read_reg_1043 );

    SC_METHOD(thread_tmp_9_fu_567_p2);
    sensitive << ( length_reg_955 );
    sensitive << ( i_reg_364 );

    SC_METHOD(thread_tmp_fu_403_p3);
    sensitive << ( length_reg_955 );

    SC_METHOD(thread_tmp_s_fu_572_p1);
    sensitive << ( tmp_9_reg_1053 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( length_a_rsp_empty_n );
    sensitive << ( b_c_req_full_n );
    sensitive << ( b_c_rsp_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_50_fu_480_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( ap_CS_fsm_state28 );
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( ap_CS_fsm_state33 );
    sensitive << ( ap_CS_fsm_state38 );
    sensitive << ( ap_CS_fsm_state40 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( ap_CS_fsm_state46 );
    sensitive << ( tmp_39_fu_894_p2 );
    sensitive << ( ap_CS_fsm_state49 );
    sensitive << ( ap_CS_fsm_state45 );
    sensitive << ( ap_CS_fsm_state51 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( ap_CS_fsm_state35 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "000000000000000000000000000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "rocc0_vadd_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, length_a_req_din, "(port)length_a_req_din");
    sc_trace(mVcdFile, length_a_req_full_n, "(port)length_a_req_full_n");
    sc_trace(mVcdFile, length_a_req_write, "(port)length_a_req_write");
    sc_trace(mVcdFile, length_a_rsp_empty_n, "(port)length_a_rsp_empty_n");
    sc_trace(mVcdFile, length_a_rsp_read, "(port)length_a_rsp_read");
    sc_trace(mVcdFile, length_a_address, "(port)length_a_address");
    sc_trace(mVcdFile, length_a_datain, "(port)length_a_datain");
    sc_trace(mVcdFile, length_a_dataout, "(port)length_a_dataout");
    sc_trace(mVcdFile, length_a_size, "(port)length_a_size");
    sc_trace(mVcdFile, b_c_req_din, "(port)b_c_req_din");
    sc_trace(mVcdFile, b_c_req_full_n, "(port)b_c_req_full_n");
    sc_trace(mVcdFile, b_c_req_write, "(port)b_c_req_write");
    sc_trace(mVcdFile, b_c_rsp_empty_n, "(port)b_c_rsp_empty_n");
    sc_trace(mVcdFile, b_c_rsp_read, "(port)b_c_rsp_read");
    sc_trace(mVcdFile, b_c_address, "(port)b_c_address");
    sc_trace(mVcdFile, b_c_datain, "(port)b_c_datain");
    sc_trace(mVcdFile, b_c_dataout, "(port)b_c_dataout");
    sc_trace(mVcdFile, b_c_size, "(port)b_c_size");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, length_reg_955, "length_reg_955");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_44_reg_970, "tmp_44_reg_970");
    sc_trace(mVcdFile, i_5_fu_396_p3, "i_5_fu_396_p3");
    sc_trace(mVcdFile, i_5_reg_975, "i_5_reg_975");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_49_fu_472_p3, "tmp_49_fu_472_p3");
    sc_trace(mVcdFile, tmp_49_reg_980, "tmp_49_reg_980");
    sc_trace(mVcdFile, tmp_1_fu_485_p2, "tmp_1_fu_485_p2");
    sc_trace(mVcdFile, tmp_1_reg_988, "tmp_1_reg_988");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_50_fu_480_p2, "tmp_50_fu_480_p2");
    sc_trace(mVcdFile, length_a_addr_reg_994, "length_a_addr_reg_994");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, length_a_addr_read_reg_1006, "length_a_addr_read_reg_1006");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_block_state8, "ap_block_state8");
    sc_trace(mVcdFile, b_c_addr_read_reg_1011, "b_c_addr_read_reg_1011");
    sc_trace(mVcdFile, tmp_3_fu_521_p2, "tmp_3_fu_521_p2");
    sc_trace(mVcdFile, tmp_3_reg_1016, "tmp_3_reg_1016");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, tmp_5_fu_525_p2, "tmp_5_fu_525_p2");
    sc_trace(mVcdFile, tmp_5_reg_1021, "tmp_5_reg_1021");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, length_a_addr_1_read_reg_1038, "length_a_addr_1_read_reg_1038");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_block_state13, "ap_block_state13");
    sc_trace(mVcdFile, b_c_addr_2_read_reg_1043, "b_c_addr_2_read_reg_1043");
    sc_trace(mVcdFile, tmp_8_fu_563_p2, "tmp_8_fu_563_p2");
    sc_trace(mVcdFile, tmp_8_reg_1048, "tmp_8_reg_1048");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, tmp_9_fu_567_p2, "tmp_9_fu_567_p2");
    sc_trace(mVcdFile, tmp_9_reg_1053, "tmp_9_reg_1053");
    sc_trace(mVcdFile, tmp_4_fu_582_p2, "tmp_4_fu_582_p2");
    sc_trace(mVcdFile, tmp_4_reg_1058, "tmp_4_reg_1058");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, length_a_addr_2_read_reg_1075, "length_a_addr_2_read_reg_1075");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, ap_block_state18, "ap_block_state18");
    sc_trace(mVcdFile, b_c_addr_4_read_reg_1080, "b_c_addr_4_read_reg_1080");
    sc_trace(mVcdFile, tmp_11_fu_612_p2, "tmp_11_fu_612_p2");
    sc_trace(mVcdFile, tmp_11_reg_1085, "tmp_11_reg_1085");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, tmp_12_fu_616_p2, "tmp_12_fu_616_p2");
    sc_trace(mVcdFile, tmp_12_reg_1090, "tmp_12_reg_1090");
    sc_trace(mVcdFile, tmp_14_fu_630_p2, "tmp_14_fu_630_p2");
    sc_trace(mVcdFile, tmp_14_reg_1095, "tmp_14_reg_1095");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, length_a_addr_3_reg_1101, "length_a_addr_3_reg_1101");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, length_a_addr_3_read_reg_1113, "length_a_addr_3_read_reg_1113");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, ap_block_state23, "ap_block_state23");
    sc_trace(mVcdFile, b_c_addr_6_read_reg_1118, "b_c_addr_6_read_reg_1118");
    sc_trace(mVcdFile, tmp_16_fu_666_p2, "tmp_16_fu_666_p2");
    sc_trace(mVcdFile, tmp_16_reg_1123, "tmp_16_reg_1123");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, tmp_17_fu_670_p2, "tmp_17_fu_670_p2");
    sc_trace(mVcdFile, tmp_17_reg_1128, "tmp_17_reg_1128");
    sc_trace(mVcdFile, tmp_19_fu_684_p2, "tmp_19_fu_684_p2");
    sc_trace(mVcdFile, tmp_19_reg_1133, "tmp_19_reg_1133");
    sc_trace(mVcdFile, ap_CS_fsm_state26, "ap_CS_fsm_state26");
    sc_trace(mVcdFile, length_a_addr_4_read_reg_1150, "length_a_addr_4_read_reg_1150");
    sc_trace(mVcdFile, ap_CS_fsm_state28, "ap_CS_fsm_state28");
    sc_trace(mVcdFile, ap_block_state28, "ap_block_state28");
    sc_trace(mVcdFile, b_c_addr_8_read_reg_1155, "b_c_addr_8_read_reg_1155");
    sc_trace(mVcdFile, tmp_21_fu_714_p2, "tmp_21_fu_714_p2");
    sc_trace(mVcdFile, tmp_21_reg_1160, "tmp_21_reg_1160");
    sc_trace(mVcdFile, ap_CS_fsm_state29, "ap_CS_fsm_state29");
    sc_trace(mVcdFile, tmp_22_fu_718_p2, "tmp_22_fu_718_p2");
    sc_trace(mVcdFile, tmp_22_reg_1165, "tmp_22_reg_1165");
    sc_trace(mVcdFile, tmp_24_fu_732_p2, "tmp_24_fu_732_p2");
    sc_trace(mVcdFile, tmp_24_reg_1170, "tmp_24_reg_1170");
    sc_trace(mVcdFile, ap_CS_fsm_state30, "ap_CS_fsm_state30");
    sc_trace(mVcdFile, length_a_addr_5_reg_1176, "length_a_addr_5_reg_1176");
    sc_trace(mVcdFile, ap_CS_fsm_state31, "ap_CS_fsm_state31");
    sc_trace(mVcdFile, length_a_addr_5_read_reg_1188, "length_a_addr_5_read_reg_1188");
    sc_trace(mVcdFile, ap_CS_fsm_state33, "ap_CS_fsm_state33");
    sc_trace(mVcdFile, ap_block_state33, "ap_block_state33");
    sc_trace(mVcdFile, b_c_addr_10_read_reg_1193, "b_c_addr_10_read_reg_1193");
    sc_trace(mVcdFile, tmp_26_fu_768_p2, "tmp_26_fu_768_p2");
    sc_trace(mVcdFile, tmp_26_reg_1198, "tmp_26_reg_1198");
    sc_trace(mVcdFile, ap_CS_fsm_state34, "ap_CS_fsm_state34");
    sc_trace(mVcdFile, tmp_27_fu_772_p2, "tmp_27_fu_772_p2");
    sc_trace(mVcdFile, tmp_27_reg_1203, "tmp_27_reg_1203");
    sc_trace(mVcdFile, tmp_29_fu_786_p2, "tmp_29_fu_786_p2");
    sc_trace(mVcdFile, tmp_29_reg_1208, "tmp_29_reg_1208");
    sc_trace(mVcdFile, ap_CS_fsm_state36, "ap_CS_fsm_state36");
    sc_trace(mVcdFile, length_a_addr_6_read_reg_1225, "length_a_addr_6_read_reg_1225");
    sc_trace(mVcdFile, ap_CS_fsm_state38, "ap_CS_fsm_state38");
    sc_trace(mVcdFile, ap_block_state38, "ap_block_state38");
    sc_trace(mVcdFile, b_c_addr_12_read_reg_1230, "b_c_addr_12_read_reg_1230");
    sc_trace(mVcdFile, tmp_31_fu_816_p2, "tmp_31_fu_816_p2");
    sc_trace(mVcdFile, tmp_31_reg_1235, "tmp_31_reg_1235");
    sc_trace(mVcdFile, ap_CS_fsm_state39, "ap_CS_fsm_state39");
    sc_trace(mVcdFile, tmp_32_fu_820_p2, "tmp_32_fu_820_p2");
    sc_trace(mVcdFile, tmp_32_reg_1240, "tmp_32_reg_1240");
    sc_trace(mVcdFile, tmp_34_fu_834_p2, "tmp_34_fu_834_p2");
    sc_trace(mVcdFile, tmp_34_reg_1245, "tmp_34_reg_1245");
    sc_trace(mVcdFile, ap_CS_fsm_state40, "ap_CS_fsm_state40");
    sc_trace(mVcdFile, length_a_addr_7_reg_1251, "length_a_addr_7_reg_1251");
    sc_trace(mVcdFile, i_2_fu_860_p2, "i_2_fu_860_p2");
    sc_trace(mVcdFile, i_2_reg_1257, "i_2_reg_1257");
    sc_trace(mVcdFile, ap_CS_fsm_state41, "ap_CS_fsm_state41");
    sc_trace(mVcdFile, tmp_37_fu_876_p2, "tmp_37_fu_876_p2");
    sc_trace(mVcdFile, tmp_37_reg_1268, "tmp_37_reg_1268");
    sc_trace(mVcdFile, length_a_addr_7_read_reg_1273, "length_a_addr_7_read_reg_1273");
    sc_trace(mVcdFile, ap_CS_fsm_state43, "ap_CS_fsm_state43");
    sc_trace(mVcdFile, ap_block_state43, "ap_block_state43");
    sc_trace(mVcdFile, b_c_addr_14_read_reg_1278, "b_c_addr_14_read_reg_1278");
    sc_trace(mVcdFile, tmp_36_fu_880_p2, "tmp_36_fu_880_p2");
    sc_trace(mVcdFile, tmp_36_reg_1283, "tmp_36_reg_1283");
    sc_trace(mVcdFile, ap_CS_fsm_state44, "ap_CS_fsm_state44");
    sc_trace(mVcdFile, length_a_addr_8_reg_1291, "length_a_addr_8_reg_1291");
    sc_trace(mVcdFile, ap_CS_fsm_state46, "ap_CS_fsm_state46");
    sc_trace(mVcdFile, tmp_39_fu_894_p2, "tmp_39_fu_894_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state47, "ap_CS_fsm_state47");
    sc_trace(mVcdFile, length_a_addr_8_read_reg_1303, "length_a_addr_8_read_reg_1303");
    sc_trace(mVcdFile, ap_CS_fsm_state49, "ap_CS_fsm_state49");
    sc_trace(mVcdFile, ap_block_state49, "ap_block_state49");
    sc_trace(mVcdFile, b_c_addr_16_read_reg_1308, "b_c_addr_16_read_reg_1308");
    sc_trace(mVcdFile, tmp_41_fu_930_p2, "tmp_41_fu_930_p2");
    sc_trace(mVcdFile, tmp_41_reg_1313, "tmp_41_reg_1313");
    sc_trace(mVcdFile, ap_CS_fsm_state50, "ap_CS_fsm_state50");
    sc_trace(mVcdFile, tmp_42_fu_934_p2, "tmp_42_fu_934_p2");
    sc_trace(mVcdFile, tmp_42_reg_1318, "tmp_42_reg_1318");
    sc_trace(mVcdFile, i_3_fu_939_p2, "i_3_fu_939_p2");
    sc_trace(mVcdFile, i_3_reg_1323, "i_3_reg_1323");
    sc_trace(mVcdFile, i_reg_364, "i_reg_364");
    sc_trace(mVcdFile, ap_CS_fsm_state45, "ap_CS_fsm_state45");
    sc_trace(mVcdFile, i_1_reg_376, "i_1_reg_376");
    sc_trace(mVcdFile, ap_CS_fsm_state51, "ap_CS_fsm_state51");
    sc_trace(mVcdFile, a_0_sum1_cast_fu_501_p1, "a_0_sum1_cast_fu_501_p1");
    sc_trace(mVcdFile, tmp_2_fu_511_p1, "tmp_2_fu_511_p1");
    sc_trace(mVcdFile, tmp_6_fu_529_p1, "tmp_6_fu_529_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, a_0_sum2_fu_543_p2, "a_0_sum2_fu_543_p2");
    sc_trace(mVcdFile, tmp_7_fu_539_p1, "tmp_7_fu_539_p1");
    sc_trace(mVcdFile, tmp_s_fu_572_p1, "tmp_s_fu_572_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, a_0_sum3_fu_592_p2, "a_0_sum3_fu_592_p2");
    sc_trace(mVcdFile, tmp_10_fu_588_p1, "tmp_10_fu_588_p1");
    sc_trace(mVcdFile, tmp_13_fu_620_p1, "tmp_13_fu_620_p1");
    sc_trace(mVcdFile, a_0_sum6_cast_fu_646_p1, "a_0_sum6_cast_fu_646_p1");
    sc_trace(mVcdFile, tmp_15_fu_656_p1, "tmp_15_fu_656_p1");
    sc_trace(mVcdFile, tmp_18_fu_674_p1, "tmp_18_fu_674_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, a_0_sum4_fu_694_p2, "a_0_sum4_fu_694_p2");
    sc_trace(mVcdFile, tmp_20_fu_690_p1, "tmp_20_fu_690_p1");
    sc_trace(mVcdFile, tmp_23_fu_722_p1, "tmp_23_fu_722_p1");
    sc_trace(mVcdFile, a_0_sum9_cast_fu_748_p1, "a_0_sum9_cast_fu_748_p1");
    sc_trace(mVcdFile, tmp_25_fu_758_p1, "tmp_25_fu_758_p1");
    sc_trace(mVcdFile, tmp_28_fu_776_p1, "tmp_28_fu_776_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state35, "ap_CS_fsm_state35");
    sc_trace(mVcdFile, a_0_sum5_fu_796_p2, "a_0_sum5_fu_796_p2");
    sc_trace(mVcdFile, tmp_30_fu_792_p1, "tmp_30_fu_792_p1");
    sc_trace(mVcdFile, tmp_33_fu_824_p1, "tmp_33_fu_824_p1");
    sc_trace(mVcdFile, a_0_sum7_cast_fu_850_p1, "a_0_sum7_cast_fu_850_p1");
    sc_trace(mVcdFile, tmp_35_fu_866_p1, "tmp_35_fu_866_p1");
    sc_trace(mVcdFile, tmp_38_fu_884_p1, "tmp_38_fu_884_p1");
    sc_trace(mVcdFile, a_0_sum_cast_fu_909_p1, "a_0_sum_cast_fu_909_p1");
    sc_trace(mVcdFile, tmp_40_fu_919_p1, "tmp_40_fu_919_p1");
    sc_trace(mVcdFile, tmp_43_fu_945_p1, "tmp_43_fu_945_p1");
    sc_trace(mVcdFile, i_5_op_op_fu_410_p2, "i_5_op_op_fu_410_p2");
    sc_trace(mVcdFile, p_neg_fu_424_p2, "p_neg_fu_424_p2");
    sc_trace(mVcdFile, p_lshr_fu_430_p4, "p_lshr_fu_430_p4");
    sc_trace(mVcdFile, tmp_45_fu_416_p3, "tmp_45_fu_416_p3");
    sc_trace(mVcdFile, p_neg_t_fu_440_p2, "p_neg_t_fu_440_p2");
    sc_trace(mVcdFile, tmp_46_fu_446_p4, "tmp_46_fu_446_p4");
    sc_trace(mVcdFile, tmp_fu_403_p3, "tmp_fu_403_p3");
    sc_trace(mVcdFile, tmp_47_fu_456_p3, "tmp_47_fu_456_p3");
    sc_trace(mVcdFile, tmp_48_fu_464_p3, "tmp_48_fu_464_p3");
    sc_trace(mVcdFile, tmp_2_cast_fu_491_p1, "tmp_2_cast_fu_491_p1");
    sc_trace(mVcdFile, a_0_sum1_fu_495_p2, "a_0_sum1_fu_495_p2");
    sc_trace(mVcdFile, tmp_17_cast_fu_636_p1, "tmp_17_cast_fu_636_p1");
    sc_trace(mVcdFile, a_0_sum6_fu_640_p2, "a_0_sum6_fu_640_p2");
    sc_trace(mVcdFile, tmp_29_cast_fu_738_p1, "tmp_29_cast_fu_738_p1");
    sc_trace(mVcdFile, a_0_sum9_fu_742_p2, "a_0_sum9_fu_742_p2");
    sc_trace(mVcdFile, tmp_41_cast_fu_840_p1, "tmp_41_cast_fu_840_p1");
    sc_trace(mVcdFile, a_0_sum7_fu_844_p2, "a_0_sum7_fu_844_p2");
    sc_trace(mVcdFile, tmp_47_cast_fu_899_p1, "tmp_47_cast_fu_899_p1");
    sc_trace(mVcdFile, a_0_sum_fu_903_p2, "a_0_sum_fu_903_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("rocc0_vadd.hdltvin.dat");
    mHdltvoutHandle.open("rocc0_vadd.hdltvout.dat");
}

rocc0_vadd::~rocc0_vadd() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void rocc0_vadd::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(tmp_50_fu_480_p2.read(), ap_const_lv1_1))) {
        i_1_reg_376 = i_5_reg_975.read();
    } else if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state51.read()))) {
        i_1_reg_376 = i_3_reg_1323.read();
    }
    if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state45.read()))) {
        i_reg_364 = i_2_reg_1257.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_reg_364 = ap_const_lv32_0;
    }
    if ((!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read()))) {
        b_c_addr_10_read_reg_1193 = b_c_datain.read();
        length_a_addr_5_read_reg_1188 = length_a_datain.read();
    }
    if ((!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read()))) {
        b_c_addr_12_read_reg_1230 = b_c_datain.read();
        length_a_addr_6_read_reg_1225 = length_a_datain.read();
    }
    if ((!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read()))) {
        b_c_addr_14_read_reg_1278 = b_c_datain.read();
        length_a_addr_7_read_reg_1273 = length_a_datain.read();
    }
    if ((!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state49.read()))) {
        b_c_addr_16_read_reg_1308 = b_c_datain.read();
        length_a_addr_8_read_reg_1303 = length_a_datain.read();
    }
    if ((!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        b_c_addr_2_read_reg_1043 = b_c_datain.read();
        length_a_addr_1_read_reg_1038 = length_a_datain.read();
    }
    if ((!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        b_c_addr_4_read_reg_1080 = b_c_datain.read();
        length_a_addr_2_read_reg_1075 = length_a_datain.read();
    }
    if ((!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()))) {
        b_c_addr_6_read_reg_1118 = b_c_datain.read();
        length_a_addr_3_read_reg_1113 = length_a_datain.read();
    }
    if ((!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read()))) {
        b_c_addr_8_read_reg_1155 = b_c_datain.read();
        length_a_addr_4_read_reg_1150 = length_a_datain.read();
    }
    if ((!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        b_c_addr_read_reg_1011 = b_c_datain.read();
        length_a_addr_read_reg_1006 = length_a_datain.read();
    }
    if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state40.read()))) {
        i_2_reg_1257 = i_2_fu_860_p2.read();
        length_a_addr_7_reg_1251 = a_0_sum7_cast_fu_850_p1.read();
        tmp_34_reg_1245 = tmp_34_fu_834_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state50.read())) {
        i_3_reg_1323 = i_3_fu_939_p2.read();
        tmp_41_reg_1313 = tmp_41_fu_930_p2.read();
        tmp_42_reg_1318 = tmp_42_fu_934_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_5_reg_975 = i_5_fu_396_p3.read();
        tmp_49_reg_980 = tmp_49_fu_472_p3.read();
    }
    if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        length_a_addr_3_reg_1101 = a_0_sum6_cast_fu_646_p1.read();
        tmp_14_reg_1095 = tmp_14_fu_630_p2.read();
    }
    if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read()))) {
        length_a_addr_5_reg_1176 = a_0_sum9_cast_fu_748_p1.read();
        tmp_24_reg_1170 = tmp_24_fu_732_p2.read();
    }
    if ((esl_seteq<1,1,1>(tmp_39_fu_894_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state46.read()))) {
        length_a_addr_8_reg_1291 = a_0_sum_cast_fu_909_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(tmp_50_fu_480_p2.read(), ap_const_lv1_0))) {
        length_a_addr_reg_994 = a_0_sum1_cast_fu_501_p1.read();
        tmp_1_reg_988 = tmp_1_fu_485_p2.read();
    }
    if ((esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        length_reg_955 = length_a_datain.read();
        tmp_44_reg_970 = length_a_datain.read().range(31, 3);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        tmp_11_reg_1085 = tmp_11_fu_612_p2.read();
        tmp_12_reg_1090 = tmp_12_fu_616_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        tmp_16_reg_1123 = tmp_16_fu_666_p2.read();
        tmp_17_reg_1128 = tmp_17_fu_670_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        tmp_19_reg_1133 = tmp_19_fu_684_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read())) {
        tmp_21_reg_1160 = tmp_21_fu_714_p2.read();
        tmp_22_reg_1165 = tmp_22_fu_718_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state34.read())) {
        tmp_26_reg_1198 = tmp_26_fu_768_p2.read();
        tmp_27_reg_1203 = tmp_27_fu_772_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state36.read())) {
        tmp_29_reg_1208 = tmp_29_fu_786_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state39.read())) {
        tmp_31_reg_1235 = tmp_31_fu_816_p2.read();
        tmp_32_reg_1240 = tmp_32_fu_820_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read())) {
        tmp_36_reg_1283 = tmp_36_fu_880_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read())) {
        tmp_37_reg_1268 = tmp_37_fu_876_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        tmp_3_reg_1016 = tmp_3_fu_521_p2.read();
        tmp_5_reg_1021 = tmp_5_fu_525_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        tmp_4_reg_1058 = tmp_4_fu_582_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        tmp_8_reg_1048 = tmp_8_fu_563_p2.read();
        tmp_9_reg_1053 = tmp_9_fu_567_p2.read();
    }
}

void rocc0_vadd::thread_a_0_sum1_cast_fu_501_p1() {
    a_0_sum1_cast_fu_501_p1 = esl_sext<64,33>(a_0_sum1_fu_495_p2.read());
}

void rocc0_vadd::thread_a_0_sum1_fu_495_p2() {
    a_0_sum1_fu_495_p2 = (!tmp_2_cast_fu_491_p1.read().is_01() || !ap_const_lv33_1.is_01())? sc_lv<33>(): (sc_bigint<33>(tmp_2_cast_fu_491_p1.read()) + sc_biguint<33>(ap_const_lv33_1));
}

void rocc0_vadd::thread_a_0_sum2_fu_543_p2() {
    a_0_sum2_fu_543_p2 = (tmp_7_fu_539_p1.read() | ap_const_lv64_1);
}

void rocc0_vadd::thread_a_0_sum3_fu_592_p2() {
    a_0_sum3_fu_592_p2 = (tmp_10_fu_588_p1.read() | ap_const_lv64_1);
}

void rocc0_vadd::thread_a_0_sum4_fu_694_p2() {
    a_0_sum4_fu_694_p2 = (tmp_20_fu_690_p1.read() | ap_const_lv64_1);
}

void rocc0_vadd::thread_a_0_sum5_fu_796_p2() {
    a_0_sum5_fu_796_p2 = (tmp_30_fu_792_p1.read() | ap_const_lv64_1);
}

void rocc0_vadd::thread_a_0_sum6_cast_fu_646_p1() {
    a_0_sum6_cast_fu_646_p1 = esl_sext<64,33>(a_0_sum6_fu_640_p2.read());
}

void rocc0_vadd::thread_a_0_sum6_fu_640_p2() {
    a_0_sum6_fu_640_p2 = (!tmp_17_cast_fu_636_p1.read().is_01() || !ap_const_lv33_1.is_01())? sc_lv<33>(): (sc_bigint<33>(tmp_17_cast_fu_636_p1.read()) + sc_biguint<33>(ap_const_lv33_1));
}

void rocc0_vadd::thread_a_0_sum7_cast_fu_850_p1() {
    a_0_sum7_cast_fu_850_p1 = esl_sext<64,33>(a_0_sum7_fu_844_p2.read());
}

void rocc0_vadd::thread_a_0_sum7_fu_844_p2() {
    a_0_sum7_fu_844_p2 = (!tmp_41_cast_fu_840_p1.read().is_01() || !ap_const_lv33_1.is_01())? sc_lv<33>(): (sc_bigint<33>(tmp_41_cast_fu_840_p1.read()) + sc_biguint<33>(ap_const_lv33_1));
}

void rocc0_vadd::thread_a_0_sum9_cast_fu_748_p1() {
    a_0_sum9_cast_fu_748_p1 = esl_sext<64,33>(a_0_sum9_fu_742_p2.read());
}

void rocc0_vadd::thread_a_0_sum9_fu_742_p2() {
    a_0_sum9_fu_742_p2 = (!tmp_29_cast_fu_738_p1.read().is_01() || !ap_const_lv33_1.is_01())? sc_lv<33>(): (sc_bigint<33>(tmp_29_cast_fu_738_p1.read()) + sc_biguint<33>(ap_const_lv33_1));
}

void rocc0_vadd::thread_a_0_sum_cast_fu_909_p1() {
    a_0_sum_cast_fu_909_p1 = esl_sext<64,33>(a_0_sum_fu_903_p2.read());
}

void rocc0_vadd::thread_a_0_sum_fu_903_p2() {
    a_0_sum_fu_903_p2 = (!tmp_47_cast_fu_899_p1.read().is_01() || !ap_const_lv33_1.is_01())? sc_lv<33>(): (sc_bigint<33>(tmp_47_cast_fu_899_p1.read()) + sc_biguint<33>(ap_const_lv33_1));
}

void rocc0_vadd::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void rocc0_vadd::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void rocc0_vadd::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void rocc0_vadd::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void rocc0_vadd::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void rocc0_vadd::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void rocc0_vadd::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void rocc0_vadd::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void rocc0_vadd::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void rocc0_vadd::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void rocc0_vadd::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void rocc0_vadd::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void rocc0_vadd::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void rocc0_vadd::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read()[24];
}

void rocc0_vadd::thread_ap_CS_fsm_state26() {
    ap_CS_fsm_state26 = ap_CS_fsm.read()[25];
}

void rocc0_vadd::thread_ap_CS_fsm_state28() {
    ap_CS_fsm_state28 = ap_CS_fsm.read()[27];
}

void rocc0_vadd::thread_ap_CS_fsm_state29() {
    ap_CS_fsm_state29 = ap_CS_fsm.read()[28];
}

void rocc0_vadd::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void rocc0_vadd::thread_ap_CS_fsm_state30() {
    ap_CS_fsm_state30 = ap_CS_fsm.read()[29];
}

void rocc0_vadd::thread_ap_CS_fsm_state31() {
    ap_CS_fsm_state31 = ap_CS_fsm.read()[30];
}

void rocc0_vadd::thread_ap_CS_fsm_state33() {
    ap_CS_fsm_state33 = ap_CS_fsm.read()[32];
}

void rocc0_vadd::thread_ap_CS_fsm_state34() {
    ap_CS_fsm_state34 = ap_CS_fsm.read()[33];
}

void rocc0_vadd::thread_ap_CS_fsm_state35() {
    ap_CS_fsm_state35 = ap_CS_fsm.read()[34];
}

void rocc0_vadd::thread_ap_CS_fsm_state36() {
    ap_CS_fsm_state36 = ap_CS_fsm.read()[35];
}

void rocc0_vadd::thread_ap_CS_fsm_state38() {
    ap_CS_fsm_state38 = ap_CS_fsm.read()[37];
}

void rocc0_vadd::thread_ap_CS_fsm_state39() {
    ap_CS_fsm_state39 = ap_CS_fsm.read()[38];
}

void rocc0_vadd::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void rocc0_vadd::thread_ap_CS_fsm_state40() {
    ap_CS_fsm_state40 = ap_CS_fsm.read()[39];
}

void rocc0_vadd::thread_ap_CS_fsm_state41() {
    ap_CS_fsm_state41 = ap_CS_fsm.read()[40];
}

void rocc0_vadd::thread_ap_CS_fsm_state43() {
    ap_CS_fsm_state43 = ap_CS_fsm.read()[42];
}

void rocc0_vadd::thread_ap_CS_fsm_state44() {
    ap_CS_fsm_state44 = ap_CS_fsm.read()[43];
}

void rocc0_vadd::thread_ap_CS_fsm_state45() {
    ap_CS_fsm_state45 = ap_CS_fsm.read()[44];
}

void rocc0_vadd::thread_ap_CS_fsm_state46() {
    ap_CS_fsm_state46 = ap_CS_fsm.read()[45];
}

void rocc0_vadd::thread_ap_CS_fsm_state47() {
    ap_CS_fsm_state47 = ap_CS_fsm.read()[46];
}

void rocc0_vadd::thread_ap_CS_fsm_state49() {
    ap_CS_fsm_state49 = ap_CS_fsm.read()[48];
}

void rocc0_vadd::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void rocc0_vadd::thread_ap_CS_fsm_state50() {
    ap_CS_fsm_state50 = ap_CS_fsm.read()[49];
}

void rocc0_vadd::thread_ap_CS_fsm_state51() {
    ap_CS_fsm_state51 = ap_CS_fsm.read()[50];
}

void rocc0_vadd::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void rocc0_vadd::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void rocc0_vadd::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void rocc0_vadd::thread_ap_block_state13() {
    ap_block_state13 = (esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0));
}

void rocc0_vadd::thread_ap_block_state18() {
    ap_block_state18 = (esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0));
}

void rocc0_vadd::thread_ap_block_state23() {
    ap_block_state23 = (esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0));
}

void rocc0_vadd::thread_ap_block_state28() {
    ap_block_state28 = (esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0));
}

void rocc0_vadd::thread_ap_block_state33() {
    ap_block_state33 = (esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0));
}

void rocc0_vadd::thread_ap_block_state38() {
    ap_block_state38 = (esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0));
}

void rocc0_vadd::thread_ap_block_state43() {
    ap_block_state43 = (esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0));
}

void rocc0_vadd::thread_ap_block_state49() {
    ap_block_state49 = (esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0));
}

void rocc0_vadd::thread_ap_block_state8() {
    ap_block_state8 = (esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0));
}

void rocc0_vadd::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state46.read()) && 
         esl_seteq<1,1,1>(tmp_39_fu_894_p2.read(), ap_const_lv1_0))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void rocc0_vadd::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void rocc0_vadd::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state46.read()) && 
         esl_seteq<1,1,1>(tmp_39_fu_894_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void rocc0_vadd::thread_ap_return() {
    ap_return = ap_const_lv32_0;
}

void rocc0_vadd::thread_b_c_address() {
    if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state51.read()))) {
        b_c_address =  (sc_lv<32>) (tmp_43_fu_945_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state47.read())) {
        b_c_address =  (sc_lv<32>) (tmp_40_fu_919_p1.read());
    } else if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state45.read()))) {
        b_c_address =  (sc_lv<32>) (tmp_38_fu_884_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read())) {
        b_c_address =  (sc_lv<32>) (tmp_35_fu_866_p1.read());
    } else if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state40.read()))) {
        b_c_address =  (sc_lv<32>) (tmp_33_fu_824_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state36.read())) {
        b_c_address =  (sc_lv<32>) (tmp_30_fu_792_p1.read());
    } else if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state35.read()))) {
        b_c_address =  (sc_lv<32>) (tmp_28_fu_776_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read())) {
        b_c_address =  (sc_lv<32>) (tmp_25_fu_758_p1.read());
    } else if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read()))) {
        b_c_address =  (sc_lv<32>) (tmp_23_fu_722_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        b_c_address =  (sc_lv<32>) (tmp_20_fu_690_p1.read());
    } else if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read()))) {
        b_c_address =  (sc_lv<32>) (tmp_18_fu_674_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        b_c_address =  (sc_lv<32>) (tmp_15_fu_656_p1.read());
    } else if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        b_c_address =  (sc_lv<32>) (tmp_13_fu_620_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        b_c_address =  (sc_lv<32>) (tmp_10_fu_588_p1.read());
    } else if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        b_c_address =  (sc_lv<32>) (tmp_s_fu_572_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        b_c_address =  (sc_lv<32>) (tmp_7_fu_539_p1.read());
    } else if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        b_c_address =  (sc_lv<32>) (tmp_6_fu_529_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        b_c_address =  (sc_lv<32>) (tmp_2_fu_511_p1.read());
    } else {
        b_c_address = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void rocc0_vadd::thread_b_c_dataout() {
    if (esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1)) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state51.read())) {
            b_c_dataout = tmp_41_reg_1313.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state45.read())) {
            b_c_dataout = tmp_36_reg_1283.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state40.read())) {
            b_c_dataout = tmp_31_reg_1235.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state35.read())) {
            b_c_dataout = tmp_26_reg_1198.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read())) {
            b_c_dataout = tmp_21_reg_1160.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
            b_c_dataout = tmp_16_reg_1123.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
            b_c_dataout = tmp_11_reg_1085.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
            b_c_dataout = tmp_8_reg_1048.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
            b_c_dataout = tmp_3_reg_1016.read();
        } else {
            b_c_dataout = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        b_c_dataout = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void rocc0_vadd::thread_b_c_req_din() {
    if (((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) || 
         (esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read())) || 
         (esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state40.read())) || 
         (esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state45.read())) || 
         (esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state51.read())) || 
         (esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) || 
         (esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) || 
         (esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) || 
         (esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state35.read())))) {
        b_c_req_din = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state36.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state47.read()))) {
        b_c_req_din = ap_const_logic_0;
    } else {
        b_c_req_din = ap_const_logic_0;
    }
}

void rocc0_vadd::thread_b_c_req_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         (esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) || 
         (esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state36.read()) || 
         (esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state40.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state47.read()) || 
         (esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state45.read())) || 
         (esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state51.read())) || 
         (esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) || 
         (esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) || 
         (esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) || 
         (esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state35.read())))) {
        b_c_req_write = ap_const_logic_1;
    } else {
        b_c_req_write = ap_const_logic_0;
    }
}

void rocc0_vadd::thread_b_c_rsp_read() {
    if (((!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) || 
         (!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) || 
         (!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) || 
         (!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) || 
         (!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) || 
         (!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read())) || 
         (!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read())) || 
         (!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) || 
         (!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state49.read())))) {
        b_c_rsp_read = ap_const_logic_1;
    } else {
        b_c_rsp_read = ap_const_logic_0;
    }
}

void rocc0_vadd::thread_b_c_size() {
    b_c_size = ap_const_lv32_1;
}

void rocc0_vadd::thread_i_2_fu_860_p2() {
    i_2_fu_860_p2 = (!i_reg_364.read().is_01() || !ap_const_lv32_8.is_01())? sc_lv<32>(): (sc_bigint<32>(i_reg_364.read()) + sc_biguint<32>(ap_const_lv32_8));
}

void rocc0_vadd::thread_i_3_fu_939_p2() {
    i_3_fu_939_p2 = (!i_1_reg_376.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(i_1_reg_376.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void rocc0_vadd::thread_i_5_fu_396_p3() {
    i_5_fu_396_p3 = esl_concat<29,3>(tmp_44_reg_970.read(), ap_const_lv3_0);
}

void rocc0_vadd::thread_i_5_op_op_fu_410_p2() {
    i_5_op_op_fu_410_p2 = (!i_5_fu_396_p3.read().is_01() || !ap_const_lv32_7.is_01())? sc_lv<32>(): (sc_biguint<32>(i_5_fu_396_p3.read()) + sc_biguint<32>(ap_const_lv32_7));
}

void rocc0_vadd::thread_length_a_address() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state47.read())) {
        length_a_address =  (sc_lv<32>) (length_a_addr_8_reg_1291.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read())) {
        length_a_address =  (sc_lv<32>) (length_a_addr_7_reg_1251.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state36.read())) {
        length_a_address =  (sc_lv<32>) (a_0_sum5_fu_796_p2.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read())) {
        length_a_address =  (sc_lv<32>) (length_a_addr_5_reg_1176.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        length_a_address =  (sc_lv<32>) (a_0_sum4_fu_694_p2.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        length_a_address =  (sc_lv<32>) (length_a_addr_3_reg_1101.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        length_a_address =  (sc_lv<32>) (a_0_sum3_fu_592_p2.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        length_a_address =  (sc_lv<32>) (a_0_sum2_fu_543_p2.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        length_a_address =  (sc_lv<32>) (length_a_addr_reg_994.read());
    } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        length_a_address = ap_const_lv32_0;
    } else {
        length_a_address = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void rocc0_vadd::thread_length_a_dataout() {
    length_a_dataout = ap_const_lv32_0;
}

void rocc0_vadd::thread_length_a_req_din() {
    length_a_req_din = ap_const_logic_0;
}

void rocc0_vadd::thread_length_a_req_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state36.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state47.read()) || 
         (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())))) {
        length_a_req_write = ap_const_logic_1;
    } else {
        length_a_req_write = ap_const_logic_0;
    }
}

void rocc0_vadd::thread_length_a_rsp_read() {
    if (((esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) || 
         (!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) || 
         (!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) || 
         (!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) || 
         (!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) || 
         (!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) || 
         (!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read())) || 
         (!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read())) || 
         (!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) || 
         (!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state49.read())))) {
        length_a_rsp_read = ap_const_logic_1;
    } else {
        length_a_rsp_read = ap_const_logic_0;
    }
}

void rocc0_vadd::thread_length_a_size() {
    length_a_size = ap_const_lv32_1;
}

void rocc0_vadd::thread_p_lshr_fu_430_p4() {
    p_lshr_fu_430_p4 = p_neg_fu_424_p2.read().range(31, 3);
}

void rocc0_vadd::thread_p_neg_fu_424_p2() {
    p_neg_fu_424_p2 = (!ap_const_lv32_FFFFFFF9.is_01() || !i_5_fu_396_p3.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFF9) - sc_biguint<32>(i_5_fu_396_p3.read()));
}

void rocc0_vadd::thread_p_neg_t_fu_440_p2() {
    p_neg_t_fu_440_p2 = (!ap_const_lv29_0.is_01() || !p_lshr_fu_430_p4.read().is_01())? sc_lv<29>(): (sc_biguint<29>(ap_const_lv29_0) - sc_biguint<29>(p_lshr_fu_430_p4.read()));
}

void rocc0_vadd::thread_tmp_10_fu_588_p1() {
    tmp_10_fu_588_p1 = esl_sext<64,32>(tmp_4_fu_582_p2.read());
}

void rocc0_vadd::thread_tmp_11_fu_612_p2() {
    tmp_11_fu_612_p2 = (!b_c_addr_4_read_reg_1080.read().is_01() || !length_a_addr_2_read_reg_1075.read().is_01())? sc_lv<32>(): (sc_biguint<32>(b_c_addr_4_read_reg_1080.read()) + sc_biguint<32>(length_a_addr_2_read_reg_1075.read()));
}

void rocc0_vadd::thread_tmp_12_fu_616_p2() {
    tmp_12_fu_616_p2 = (!tmp_4_reg_1058.read().is_01() || !length_reg_955.read().is_01())? sc_lv<32>(): (sc_bigint<32>(tmp_4_reg_1058.read()) + sc_biguint<32>(length_reg_955.read()));
}

void rocc0_vadd::thread_tmp_13_fu_620_p1() {
    tmp_13_fu_620_p1 = esl_sext<64,32>(tmp_12_reg_1090.read());
}

void rocc0_vadd::thread_tmp_14_fu_630_p2() {
    tmp_14_fu_630_p2 = (i_reg_364.read() | ap_const_lv32_3);
}

void rocc0_vadd::thread_tmp_15_fu_656_p1() {
    tmp_15_fu_656_p1 = esl_sext<64,32>(tmp_14_reg_1095.read());
}

void rocc0_vadd::thread_tmp_16_fu_666_p2() {
    tmp_16_fu_666_p2 = (!b_c_addr_6_read_reg_1118.read().is_01() || !length_a_addr_3_read_reg_1113.read().is_01())? sc_lv<32>(): (sc_biguint<32>(b_c_addr_6_read_reg_1118.read()) + sc_biguint<32>(length_a_addr_3_read_reg_1113.read()));
}

void rocc0_vadd::thread_tmp_17_cast_fu_636_p1() {
    tmp_17_cast_fu_636_p1 = esl_sext<33,32>(tmp_14_fu_630_p2.read());
}

void rocc0_vadd::thread_tmp_17_fu_670_p2() {
    tmp_17_fu_670_p2 = (!tmp_14_reg_1095.read().is_01() || !length_reg_955.read().is_01())? sc_lv<32>(): (sc_bigint<32>(tmp_14_reg_1095.read()) + sc_biguint<32>(length_reg_955.read()));
}

void rocc0_vadd::thread_tmp_18_fu_674_p1() {
    tmp_18_fu_674_p1 = esl_sext<64,32>(tmp_17_reg_1128.read());
}

void rocc0_vadd::thread_tmp_19_fu_684_p2() {
    tmp_19_fu_684_p2 = (i_reg_364.read() | ap_const_lv32_4);
}

void rocc0_vadd::thread_tmp_1_fu_485_p2() {
    tmp_1_fu_485_p2 = (i_reg_364.read() | ap_const_lv32_1);
}

void rocc0_vadd::thread_tmp_20_fu_690_p1() {
    tmp_20_fu_690_p1 = esl_sext<64,32>(tmp_19_fu_684_p2.read());
}

void rocc0_vadd::thread_tmp_21_fu_714_p2() {
    tmp_21_fu_714_p2 = (!b_c_addr_8_read_reg_1155.read().is_01() || !length_a_addr_4_read_reg_1150.read().is_01())? sc_lv<32>(): (sc_biguint<32>(b_c_addr_8_read_reg_1155.read()) + sc_biguint<32>(length_a_addr_4_read_reg_1150.read()));
}

void rocc0_vadd::thread_tmp_22_fu_718_p2() {
    tmp_22_fu_718_p2 = (!tmp_19_reg_1133.read().is_01() || !length_reg_955.read().is_01())? sc_lv<32>(): (sc_bigint<32>(tmp_19_reg_1133.read()) + sc_biguint<32>(length_reg_955.read()));
}

void rocc0_vadd::thread_tmp_23_fu_722_p1() {
    tmp_23_fu_722_p1 = esl_sext<64,32>(tmp_22_reg_1165.read());
}

void rocc0_vadd::thread_tmp_24_fu_732_p2() {
    tmp_24_fu_732_p2 = (i_reg_364.read() | ap_const_lv32_5);
}

void rocc0_vadd::thread_tmp_25_fu_758_p1() {
    tmp_25_fu_758_p1 = esl_sext<64,32>(tmp_24_reg_1170.read());
}

void rocc0_vadd::thread_tmp_26_fu_768_p2() {
    tmp_26_fu_768_p2 = (!b_c_addr_10_read_reg_1193.read().is_01() || !length_a_addr_5_read_reg_1188.read().is_01())? sc_lv<32>(): (sc_biguint<32>(b_c_addr_10_read_reg_1193.read()) + sc_biguint<32>(length_a_addr_5_read_reg_1188.read()));
}

void rocc0_vadd::thread_tmp_27_fu_772_p2() {
    tmp_27_fu_772_p2 = (!tmp_24_reg_1170.read().is_01() || !length_reg_955.read().is_01())? sc_lv<32>(): (sc_bigint<32>(tmp_24_reg_1170.read()) + sc_biguint<32>(length_reg_955.read()));
}

void rocc0_vadd::thread_tmp_28_fu_776_p1() {
    tmp_28_fu_776_p1 = esl_sext<64,32>(tmp_27_reg_1203.read());
}

void rocc0_vadd::thread_tmp_29_cast_fu_738_p1() {
    tmp_29_cast_fu_738_p1 = esl_sext<33,32>(tmp_24_fu_732_p2.read());
}

void rocc0_vadd::thread_tmp_29_fu_786_p2() {
    tmp_29_fu_786_p2 = (i_reg_364.read() | ap_const_lv32_6);
}

void rocc0_vadd::thread_tmp_2_cast_fu_491_p1() {
    tmp_2_cast_fu_491_p1 = esl_sext<33,32>(tmp_1_fu_485_p2.read());
}

void rocc0_vadd::thread_tmp_2_fu_511_p1() {
    tmp_2_fu_511_p1 = esl_sext<64,32>(tmp_1_reg_988.read());
}

void rocc0_vadd::thread_tmp_30_fu_792_p1() {
    tmp_30_fu_792_p1 = esl_sext<64,32>(tmp_29_fu_786_p2.read());
}

void rocc0_vadd::thread_tmp_31_fu_816_p2() {
    tmp_31_fu_816_p2 = (!b_c_addr_12_read_reg_1230.read().is_01() || !length_a_addr_6_read_reg_1225.read().is_01())? sc_lv<32>(): (sc_biguint<32>(b_c_addr_12_read_reg_1230.read()) + sc_biguint<32>(length_a_addr_6_read_reg_1225.read()));
}

void rocc0_vadd::thread_tmp_32_fu_820_p2() {
    tmp_32_fu_820_p2 = (!tmp_29_reg_1208.read().is_01() || !length_reg_955.read().is_01())? sc_lv<32>(): (sc_bigint<32>(tmp_29_reg_1208.read()) + sc_biguint<32>(length_reg_955.read()));
}

void rocc0_vadd::thread_tmp_33_fu_824_p1() {
    tmp_33_fu_824_p1 = esl_sext<64,32>(tmp_32_reg_1240.read());
}

void rocc0_vadd::thread_tmp_34_fu_834_p2() {
    tmp_34_fu_834_p2 = (i_reg_364.read() | ap_const_lv32_7);
}

void rocc0_vadd::thread_tmp_35_fu_866_p1() {
    tmp_35_fu_866_p1 = esl_sext<64,32>(tmp_34_reg_1245.read());
}

void rocc0_vadd::thread_tmp_36_fu_880_p2() {
    tmp_36_fu_880_p2 = (!b_c_addr_14_read_reg_1278.read().is_01() || !length_a_addr_7_read_reg_1273.read().is_01())? sc_lv<32>(): (sc_biguint<32>(b_c_addr_14_read_reg_1278.read()) + sc_biguint<32>(length_a_addr_7_read_reg_1273.read()));
}

void rocc0_vadd::thread_tmp_37_fu_876_p2() {
    tmp_37_fu_876_p2 = (!tmp_34_reg_1245.read().is_01() || !length_reg_955.read().is_01())? sc_lv<32>(): (sc_bigint<32>(tmp_34_reg_1245.read()) + sc_biguint<32>(length_reg_955.read()));
}

void rocc0_vadd::thread_tmp_38_fu_884_p1() {
    tmp_38_fu_884_p1 = esl_sext<64,32>(tmp_37_reg_1268.read());
}

void rocc0_vadd::thread_tmp_39_fu_894_p2() {
    tmp_39_fu_894_p2 = (!i_1_reg_376.read().is_01() || !length_reg_955.read().is_01())? sc_lv<1>(): (sc_bigint<32>(i_1_reg_376.read()) < sc_bigint<32>(length_reg_955.read()));
}

void rocc0_vadd::thread_tmp_3_fu_521_p2() {
    tmp_3_fu_521_p2 = (!b_c_addr_read_reg_1011.read().is_01() || !length_a_addr_read_reg_1006.read().is_01())? sc_lv<32>(): (sc_biguint<32>(b_c_addr_read_reg_1011.read()) + sc_biguint<32>(length_a_addr_read_reg_1006.read()));
}

void rocc0_vadd::thread_tmp_40_fu_919_p1() {
    tmp_40_fu_919_p1 = esl_sext<64,32>(i_1_reg_376.read());
}

void rocc0_vadd::thread_tmp_41_cast_fu_840_p1() {
    tmp_41_cast_fu_840_p1 = esl_sext<33,32>(tmp_34_fu_834_p2.read());
}

void rocc0_vadd::thread_tmp_41_fu_930_p2() {
    tmp_41_fu_930_p2 = (!b_c_addr_16_read_reg_1308.read().is_01() || !length_a_addr_8_read_reg_1303.read().is_01())? sc_lv<32>(): (sc_biguint<32>(b_c_addr_16_read_reg_1308.read()) + sc_biguint<32>(length_a_addr_8_read_reg_1303.read()));
}

void rocc0_vadd::thread_tmp_42_fu_934_p2() {
    tmp_42_fu_934_p2 = (!length_reg_955.read().is_01() || !i_1_reg_376.read().is_01())? sc_lv<32>(): (sc_biguint<32>(length_reg_955.read()) + sc_bigint<32>(i_1_reg_376.read()));
}

void rocc0_vadd::thread_tmp_43_fu_945_p1() {
    tmp_43_fu_945_p1 = esl_sext<64,32>(tmp_42_reg_1318.read());
}

void rocc0_vadd::thread_tmp_45_fu_416_p3() {
    tmp_45_fu_416_p3 = i_5_op_op_fu_410_p2.read().range(31, 31);
}

void rocc0_vadd::thread_tmp_46_fu_446_p4() {
    tmp_46_fu_446_p4 = i_5_op_op_fu_410_p2.read().range(31, 3);
}

void rocc0_vadd::thread_tmp_47_cast_fu_899_p1() {
    tmp_47_cast_fu_899_p1 = esl_sext<33,32>(i_1_reg_376.read());
}

void rocc0_vadd::thread_tmp_47_fu_456_p3() {
    tmp_47_fu_456_p3 = (!tmp_45_fu_416_p3.read()[0].is_01())? sc_lv<29>(): ((tmp_45_fu_416_p3.read()[0].to_bool())? p_neg_t_fu_440_p2.read(): tmp_46_fu_446_p4.read());
}

void rocc0_vadd::thread_tmp_48_fu_464_p3() {
    tmp_48_fu_464_p3 = (!tmp_fu_403_p3.read()[0].is_01())? sc_lv<29>(): ((tmp_fu_403_p3.read()[0].to_bool())? ap_const_lv29_0: tmp_47_fu_456_p3.read());
}

void rocc0_vadd::thread_tmp_49_fu_472_p3() {
    tmp_49_fu_472_p3 = esl_concat<29,3>(tmp_48_fu_464_p3.read(), ap_const_lv3_0);
}

void rocc0_vadd::thread_tmp_4_fu_582_p2() {
    tmp_4_fu_582_p2 = (i_reg_364.read() | ap_const_lv32_2);
}

void rocc0_vadd::thread_tmp_50_fu_480_p2() {
    tmp_50_fu_480_p2 = (!i_reg_364.read().is_01() || !tmp_49_reg_980.read().is_01())? sc_lv<1>(): sc_lv<1>(i_reg_364.read() == tmp_49_reg_980.read());
}

void rocc0_vadd::thread_tmp_5_fu_525_p2() {
    tmp_5_fu_525_p2 = (!tmp_1_reg_988.read().is_01() || !length_reg_955.read().is_01())? sc_lv<32>(): (sc_bigint<32>(tmp_1_reg_988.read()) + sc_biguint<32>(length_reg_955.read()));
}

void rocc0_vadd::thread_tmp_6_fu_529_p1() {
    tmp_6_fu_529_p1 = esl_sext<64,32>(tmp_5_reg_1021.read());
}

void rocc0_vadd::thread_tmp_7_fu_539_p1() {
    tmp_7_fu_539_p1 = esl_sext<64,32>(i_reg_364.read());
}

void rocc0_vadd::thread_tmp_8_fu_563_p2() {
    tmp_8_fu_563_p2 = (!b_c_addr_2_read_reg_1043.read().is_01() || !length_a_addr_1_read_reg_1038.read().is_01())? sc_lv<32>(): (sc_biguint<32>(b_c_addr_2_read_reg_1043.read()) + sc_biguint<32>(length_a_addr_1_read_reg_1038.read()));
}

void rocc0_vadd::thread_tmp_9_fu_567_p2() {
    tmp_9_fu_567_p2 = (!length_reg_955.read().is_01() || !i_reg_364.read().is_01())? sc_lv<32>(): (sc_biguint<32>(length_reg_955.read()) + sc_bigint<32>(i_reg_364.read()));
}

void rocc0_vadd::thread_tmp_fu_403_p3() {
    tmp_fu_403_p3 = length_reg_955.read().range(31, 31);
}

void rocc0_vadd::thread_tmp_s_fu_572_p1() {
    tmp_s_fu_572_p1 = esl_sext<64,32>(tmp_9_reg_1053.read());
}

void rocc0_vadd::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(tmp_50_fu_480_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state46;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            if ((!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            if ((!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
                ap_NS_fsm = ap_ST_fsm_state14;
            } else {
                ap_NS_fsm = ap_ST_fsm_state13;
            }
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
                ap_NS_fsm = ap_ST_fsm_state16;
            } else {
                ap_NS_fsm = ap_ST_fsm_state15;
            }
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            if ((!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
                ap_NS_fsm = ap_ST_fsm_state19;
            } else {
                ap_NS_fsm = ap_ST_fsm_state18;
            }
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
                ap_NS_fsm = ap_ST_fsm_state21;
            } else {
                ap_NS_fsm = ap_ST_fsm_state20;
            }
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            if ((!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()))) {
                ap_NS_fsm = ap_ST_fsm_state24;
            } else {
                ap_NS_fsm = ap_ST_fsm_state23;
            }
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read()))) {
                ap_NS_fsm = ap_ST_fsm_state26;
            } else {
                ap_NS_fsm = ap_ST_fsm_state25;
            }
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            if ((!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read()))) {
                ap_NS_fsm = ap_ST_fsm_state29;
            } else {
                ap_NS_fsm = ap_ST_fsm_state28;
            }
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read()))) {
                ap_NS_fsm = ap_ST_fsm_state31;
            } else {
                ap_NS_fsm = ap_ST_fsm_state30;
            }
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state32;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_fsm_state33;
            break;
        case 4294967296 : 
            if ((!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read()))) {
                ap_NS_fsm = ap_ST_fsm_state34;
            } else {
                ap_NS_fsm = ap_ST_fsm_state33;
            }
            break;
        case 8589934592 : 
            ap_NS_fsm = ap_ST_fsm_state35;
            break;
        case 17179869184 : 
            if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state35.read()))) {
                ap_NS_fsm = ap_ST_fsm_state36;
            } else {
                ap_NS_fsm = ap_ST_fsm_state35;
            }
            break;
        case 34359738368 : 
            ap_NS_fsm = ap_ST_fsm_state37;
            break;
        case 68719476736 : 
            ap_NS_fsm = ap_ST_fsm_state38;
            break;
        case 137438953472 : 
            if ((!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read()))) {
                ap_NS_fsm = ap_ST_fsm_state39;
            } else {
                ap_NS_fsm = ap_ST_fsm_state38;
            }
            break;
        case 274877906944 : 
            ap_NS_fsm = ap_ST_fsm_state40;
            break;
        case 549755813888 : 
            if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state40.read()))) {
                ap_NS_fsm = ap_ST_fsm_state41;
            } else {
                ap_NS_fsm = ap_ST_fsm_state40;
            }
            break;
        case 1099511627776 : 
            ap_NS_fsm = ap_ST_fsm_state42;
            break;
        case 2199023255552 : 
            ap_NS_fsm = ap_ST_fsm_state43;
            break;
        case 4398046511104 : 
            if ((!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read()))) {
                ap_NS_fsm = ap_ST_fsm_state44;
            } else {
                ap_NS_fsm = ap_ST_fsm_state43;
            }
            break;
        case 8796093022208 : 
            ap_NS_fsm = ap_ST_fsm_state45;
            break;
        case 17592186044416 : 
            if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state45.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state45;
            }
            break;
        case 35184372088832 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state46.read()) && esl_seteq<1,1,1>(tmp_39_fu_894_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state47;
            }
            break;
        case 70368744177664 : 
            ap_NS_fsm = ap_ST_fsm_state48;
            break;
        case 140737488355328 : 
            ap_NS_fsm = ap_ST_fsm_state49;
            break;
        case 281474976710656 : 
            if ((!(esl_seteq<1,1,1>(b_c_rsp_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(length_a_rsp_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state49.read()))) {
                ap_NS_fsm = ap_ST_fsm_state50;
            } else {
                ap_NS_fsm = ap_ST_fsm_state49;
            }
            break;
        case 562949953421312 : 
            ap_NS_fsm = ap_ST_fsm_state51;
            break;
        case 1125899906842624 : 
            if ((esl_seteq<1,1,1>(b_c_req_full_n.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state51.read()))) {
                ap_NS_fsm = ap_ST_fsm_state46;
            } else {
                ap_NS_fsm = ap_ST_fsm_state51;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<51>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void rocc0_vadd::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"length_a_req_din\" :  \"" << length_a_req_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"length_a_req_full_n\" :  \"" << length_a_req_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"length_a_req_write\" :  \"" << length_a_req_write.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"length_a_rsp_empty_n\" :  \"" << length_a_rsp_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"length_a_rsp_read\" :  \"" << length_a_rsp_read.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"length_a_address\" :  \"" << length_a_address.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"length_a_datain\" :  \"" << length_a_datain.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"length_a_dataout\" :  \"" << length_a_dataout.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"length_a_size\" :  \"" << length_a_size.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"b_c_req_din\" :  \"" << b_c_req_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"b_c_req_full_n\" :  \"" << b_c_req_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"b_c_req_write\" :  \"" << b_c_req_write.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"b_c_rsp_empty_n\" :  \"" << b_c_rsp_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"b_c_rsp_read\" :  \"" << b_c_rsp_read.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"b_c_address\" :  \"" << b_c_address.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"b_c_datain\" :  \"" << b_c_datain.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"b_c_dataout\" :  \"" << b_c_dataout.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"b_c_size\" :  \"" << b_c_size.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

