// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// control
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of ap_return
//        bit 31~0 - ap_return[31:0] (Read)
// 0x18 : Data signal of a
//        bit 31~0 - a[31:0] (Read/Write)
// 0x1c : Data signal of a
//        bit 31~0 - a[63:32] (Read/Write)
// 0x20 : reserved
// 0x24 : Data signal of b
//        bit 31~0 - b[31:0] (Read/Write)
// 0x28 : Data signal of b
//        bit 31~0 - b[63:32] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of c
//        bit 31~0 - c[31:0] (Read/Write)
// 0x34 : Data signal of c
//        bit 31~0 - c[63:32] (Read/Write)
// 0x38 : reserved
// 0x3c : Data signal of length_r
//        bit 31~0 - length_r[31:0] (Read/Write)
// 0x40 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XTL0_VADD_CONTROL_ADDR_AP_CTRL       0x00
#define XTL0_VADD_CONTROL_ADDR_GIE           0x04
#define XTL0_VADD_CONTROL_ADDR_IER           0x08
#define XTL0_VADD_CONTROL_ADDR_ISR           0x0c
#define XTL0_VADD_CONTROL_ADDR_AP_RETURN     0x10
#define XTL0_VADD_CONTROL_BITS_AP_RETURN     32
#define XTL0_VADD_CONTROL_ADDR_A_DATA        0x18
#define XTL0_VADD_CONTROL_BITS_A_DATA        64
#define XTL0_VADD_CONTROL_ADDR_B_DATA        0x24
#define XTL0_VADD_CONTROL_BITS_B_DATA        64
#define XTL0_VADD_CONTROL_ADDR_C_DATA        0x30
#define XTL0_VADD_CONTROL_BITS_C_DATA        64
#define XTL0_VADD_CONTROL_ADDR_LENGTH_R_DATA 0x3c
#define XTL0_VADD_CONTROL_BITS_LENGTH_R_DATA 32

