// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xtl0_vadd.h"

extern XTl0_vadd_Config XTl0_vadd_ConfigTable[];

XTl0_vadd_Config *XTl0_vadd_LookupConfig(u16 DeviceId) {
	XTl0_vadd_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XTL0_VADD_NUM_INSTANCES; Index++) {
		if (XTl0_vadd_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XTl0_vadd_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XTl0_vadd_Initialize(XTl0_vadd *InstancePtr, u16 DeviceId) {
	XTl0_vadd_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XTl0_vadd_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XTl0_vadd_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

